### ISSUE TITLE
建议增加一个列：reference

### ISSUE THREAD

**Issue by DVKunion** [TheKingOfDuck/SBCVE#3]
放上所有对应SBCVE的公告链接，让我们来看看到底是有多少通告恶意宣传夸大漏洞影响。

**Comment by TheKingOfDuck** [comment]
> 放上所有对应SBCVE的公告链接，让我们来看看到底是有多少通告恶意宣传夸大漏洞影响。

@DVKunion 好主意，采纳了，我加一下
